api: sambastudio
llm:
  temperature: 0.1
  max_tokens_to_generate: 1024
  sambaverse_model_name: "Meta/Meta-Llama-3-8B-Instruct"
  samabaverse_select_expert: "Meta-Llama-3-8B-Instruct-4096"
  coe_routing: true

retrieval:
  chunk_size: 1000
  chunk_overlap: 200
  db_type: "faiss"

supported_experts_map:
  finance: "Finance expert"
  economics: "Finance expert"
  maths: "Math expert"
  mathematics: "Math expert"
  code generation: "Code expert"
  computer science: "Code expert"
  medical: "Medical expert"

expert_prompt: |
  <|begin_of_text|><|start_header_id|>system<|end_header_id|>
  A message can be classified as only one of the following categories: 'finance', 'economics', 'maths', 'code generation', 'legal', 'medical', 'history', 'turkish language', 'japanese language', 'literature', 'physics', 'chemistry', 'biology', 'psychology', 'sociology' or 'None of the above'.

  Examples for these categories are given below:
  - 'finance': What is the current stock price of Apple?
  - 'maths': Solve the equation 2x + 5 = 15.
  - 'code generation': Write a Python function to calculate the factorial of a number.
  - 'medical': What are the symptoms of type 2 diabetes?
  - 'Generalist': Who are you?
  - 'Generalist': What are your capabilities?
  - 'Generalist': Can you tell me a joke?

  Based on the above categories, classify this message:
  {input}

  Always remember the following instructions while classifying the given statement:
  - Think carefully and if you are not highly certain then classify the given statement as 'Generalist'
  - For 'turkish language' and 'japanese language' categories, the input may be in Turkish or Japanese respectively. Classify based on the language used, not just the content.
  - Always begin your response by putting the classified category of the given statement after '<<detected category>>:'
  - Explain your answer
  <|eot_id|><|start_header_id|>assistant<|end_header_id|>

coe_name_map:
  Finance expert: "Meta-Llama-3-8B-Instruct-4096"
  Math expert: "Meta-Llama-3-8B-Instruct-4096"
  Code expert: "Meta-Llama-3-8B-Instruct-4096"
  Medical expert: "Meta-Llama-3-8B-Instruct-4096"
  Generalist: "Meta-Llama-3-70B-Instruct"
